apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: v1
kind: Service
metadata:
  name: gitserver
  namespace: flux-system
  labels:
    app: git
spec:
  type: NodePort
  selector:
    app: git
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitserver
  namespace: flux-system
  labels:
    app: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git
  template:
    metadata:
      labels:
        app: git
    spec:
      containers:
      - name: gitserver
        image: docker.io/library/gitserver
        imagePullPolicy: Never
        ports:
        - containerPort: 22
